### PR TITLE
process can be provided with an ID

### PR DESCRIPTION
**Pull request by ClaraFuPivotal**
needed for cloudfoundry/guardian#69

### CODE REVIEW

**Comment by garden-gnome** [comment]
Hi there!

We use Pivotal Tracker to provide visibility into what our team is working on. A story for this issue has been automatically created.

The current status is as follows:

* [ ] [#140959183](https://www.pivotaltracker.com/story/show/140959183) process can be provided with an ID


This comment, as well as the labels on the issue, will be automatically updated as the status in Tracker changes.

**Comment by ClaraFuPivotal** [comment]
published org membership; you can close and reopen 👍

**Comment by williammartin** [comment]
Hi @ClaraFuPivotal and @vito Thanks for the PR, this has now been merged and is waiting acceptance before release. In future when you PR, can you make sure you provide acceptance tests either in the GQTs or preferably, the GATS. Although you wrote some integration/unit tests with the work done at Guardian, you didn't provide any test for this PR and the overall feature. 

See https://github.com/cloudfoundry/garden-integration-tests/commit/84c02f2e58a225b725b8439802209747411ab74d for an example.

**Comment by vito** [comment]
Sounds good, sorry - will remember next time.

https://github.com/cloudfoundry/guardian/pull/69 can be closed now - looks like it wasn't auto-closed by the merge for some reason

**Pull request merged**
